org: garv1805
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:670133822718:table/work

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
  CreateTask:
    handler: src/Create_work.handler
    events:
      - httpApi:
          path: /task
          method: post
  FetchTask:
    handler: src/Fetch_work.handler
    events:
      - httpApi:
          path: /task-get
          method: get
  CompleteTask:
    handler: src/complete_work.handler
    events:
      - httpApi:
          path: /task/{id}
          method: put

resources:
  Resources:
    KaamKaro:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: work
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH